// import Document, { Head } from "next/document";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Forum&family=Work+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />

        <link rel="stylesheet" href="styles.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
